// <auto-generated />
namespace VendorsPortal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _2241 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2241));
        
        string IMigrationMetadata.Id
        {
            get { return "202006102141587_2241"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
