// <auto-generated />
namespace VendorsPortal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _1908 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1908));
        
        string IMigrationMetadata.Id
        {
            get { return "202006101808484_1908"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
